version: "3.9"
services:
  api:
    build:
      context: ./apps/api
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./apps/api:/usr/src/app
    command: npm run start:dev

  web:
    build:
      context: ./apps/web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/usr/src/app
    command: npm run dev

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: jobportal
      POSTGRES_PASSWORD: jobportal
      POSTGRES_DB: jobportal
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db-data:
  minio-data:
